### ISSUE TITLE
Could not pass event PlayerLoginEvent to SuperLogger v1.6

### ISSUE THREAD

**Issue by XxCoolGamesxX** [zack6849/SuperLogger#3]
The Server is git-Spigot-15fa8e1-17a3db7 (MC: 1.8).

```
[08:40:38 INFO]: UUID of player neto8 is 9f08d7f8-bddc-36e4-97ae-9cd0b2c8a5f6
[08:40:38 ERROR]: Could not pass event PlayerLoginEvent to SuperLogger v1.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:423) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:97) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-15fa8e1-17a3db7]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
        at com.zack6849.superlogger.EventListener.onPlayerJoin(EventListener.java:161) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-15fa8e1-17a3db7]
        ... 13 more
```

**Comment by zack6849** [comment]
Is your server in whitelist mode?

**Comment by XxCoolGamesxX** [comment]
Yes 😃

**Comment by zack6849** [comment]
Yeah, that's the problem, i'll need to look into it more to fix the bug, but for some reason, it looks like superlogger doesnt like whitelisted players on 1.8, it's not a huge problem and shouldnt break anything until i fix it

**Comment by zack6849** [comment]
I've been able to verify this issue, and it's an issue with bukkit's api, seeing as bukkit isnt really maintained as far as i know, i've made an [issue on spigot's tracker](https://hub.spigotmc.org/jira/browse/SPIGOT-577) to see if we can get this fixed
