### ISSUE TITLE
ArrayIndexOutOfBoundsException in com.zack6849.superlogger.Updater.fetchData

### ISSUE THREAD

**Issue by bog500** [zack6849/SuperLogger#7]
[15:52:29] [Server thread/WARN]: [SuperLogger] Task #16 for SuperLogger v1.7.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source) ~[?:1.8.0_60]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
	at com.google.gson.JsonArray.get(JsonArray.java:101) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at com.zack6849.superlogger.Updater.fetchData(Updater.java:55) ~[?:?]
	at com.zack6849.superlogger.Main$1.run(Main.java:146) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by zack6849** [comment]
Fixed in commit 5f155b8b7329129362cb3f95bb014c799dea17a3
Thank you!
