### ISSUE TITLE
Task #7 for SuperLogger v1.7.2 generated an exception java.lang.ArrayIndexOutOfBoundsException: -

### ISSUE THREAD

**Issue by bog500** [zack6849/SuperLogger#9]
I got this error today:

[02:30:47] [Server thread/WARN]: [SuperLogger] Task #7 for SuperLogger v1.7.2 generated an exception
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source) ~[?:1.8.0_66]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_66]
	at com.google.gson.JsonArray.get(JsonArray.java:101) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at com.zack6849.superlogger.Updater.fetchData(Updater.java:55) ~[?:?]
	at com.zack6849.superlogger.Main$1.run(Main.java:145) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-76236cb-c373061]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by bog500** [comment]
The json file at

https://api.curseforge.com/servermods/files?projectIds=45448

doesn't always contains data, sometimes it's empty

**Comment by zack6849** [comment]
interesting find, i'll get around to patching the exception eventually, but that issue should fix itself after a while anyways, as it *should* refresh the data every 10 minutes or so, according to https://github.com/zack6849/SuperLogger/blob/master/src/main/java/com/zack6849/superlogger/Main.java#L145
